// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SportSpot.Persistence;

#nullable disable

namespace SportSpot.Persistence.Migrations
{
    [DbContext(typeof(SportSpotDbContext))]
    [Migration("20240618073928_make_image_params_optional")]
    partial class make_image_params_optional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SportSpot.Logic.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("Username");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<Guid?>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("SpotId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("InterestEnum")
                        .HasColumnType("integer");

                    b.Property<Guid>("SpotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpotId");

                    b.HasIndex("Username");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Spot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Spots");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Comment", b =>
                {
                    b.HasOne("SportSpot.Logic.Models.Spot", "Spot")
                        .WithMany("Comments")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSpot.Logic.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Image", b =>
                {
                    b.HasOne("SportSpot.Logic.Models.Comment", "Comment")
                        .WithMany("Images")
                        .HasForeignKey("CommentId");

                    b.HasOne("SportSpot.Logic.Models.Spot", "Spot")
                        .WithMany("Images")
                        .HasForeignKey("SpotId");

                    b.HasOne("SportSpot.Logic.Models.User", "User")
                        .WithOne("Image")
                        .HasForeignKey("SportSpot.Logic.Models.Image", "Username");

                    b.Navigation("Comment");

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Interest", b =>
                {
                    b.HasOne("SportSpot.Logic.Models.Spot", "Spot")
                        .WithMany("Interests")
                        .HasForeignKey("SpotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportSpot.Logic.Models.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Comment", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.Spot", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Images");

                    b.Navigation("Interests");
                });

            modelBuilder.Entity("SportSpot.Logic.Models.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
